facade/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls, name = "admin"),
]

main/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "main"

urlpatterns = [
	path("", views.landingpage, name = "landingpage"),
	path("stream", views.start_stream, name = "stream"),
	path("login", views.login_user, name = "login"),
	path("logout", views.logout_user, name = "logout"),
	path("register", views.register_user, name = "register"),
	path("video_feed", views.video_feed, name = "video_feed"),
	path("emotion-change", views.change_emotion, name = "change-emotion"),
	path("emotion-tracker-status-change", views.change_emotion_tracker_status, name = "emotion-tracker-status-change"),
	path("join", views.join_stream, name = "join_stream"),
	path("viewstream", views.send_stream, name = "viewstream"),
	path("writeMessage", views.writeMessage, name = "writeMessage"),
	path("readMessageViewer", views.readMessageViewer, name="readMessageViewer"),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

chat/models.py
from django.db import models


class Room(models.Model):
    """
    A room for people to chat in.
    """

    # Room title
    title = models.CharField(max_length=255)

    # If only "staff" users are allowed (is_staff on django's User)
    staff_only = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    @property
    def group_name(self):
        """
        Returns the Channels Group name that sockets should subscribe to to get sent
        messages as they are generated.
        """
        return "room-%s" % self.id

main/models.py
from django.db import models

# Create your models here.

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

		def save(self, commit=True):
			user = super(NewUserForm, self).save(commit=False)
			user.email = self.cleaned_data["email"]
			if commit:
				user.save()
				return user

chat/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import Room


@login_required
def index(request):
    """
    Root page view. This is essentially a single-page app, if you ignore the
    login and admin parts.
    """
    # Get a list of rooms, ordered alphabetically
    rooms = Room.objects.order_by("title")

    # Render that in the index template
    return render(request, "main/includes/chat.html", {
        "rooms": rooms,
    })

main/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import StreamingHttpResponse
from main.camera import VideoCamera
from main.camera import getFake
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth import logout
from django.contrib.auth import login
from django.contrib import messages
from django.shortcuts import redirect
from django.contrib.auth.forms import AuthenticationForm
from .forms import NewUserForm
from django.contrib.auth import authenticate

import os

latest_frame = None


def landingpage(request):
	return render(request, 'Html/index.html')

def login_user(request):
	if request.method == 'POST':
		form = AuthenticationForm(request=request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.info(request, f"You are now logged in as {username}")
				return redirect('/')
			else:
				messages.error(request, "Invalid username or password.")
		else:
			messages.error(request, "Invalid username or password.")
	form = AuthenticationForm()
	return render(request = request,
				template_name = "Html/login.html",
				context={"form":form})

def register_user(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			username = form.cleaned_data.get('username')
			login(request, user)
			return redirect("main:landingpage")

		else:
			for msg in form.error_messages:
				print(form.error_messages[msg])

				return render(request = request,
							template_name = "Html/register.html",
							context={"form":form})

	form = NewUserForm
	return render(request = request,
				template_name = "Html/register.html",
				context={"form":form})

def logout_user(request):
	logout(request)
	messages.info(request, "Logged out successfully!")
	return redirect("main:landingpage")

def start_stream(request):
	if (request.user.is_authenticated):
		emotionFile = open("main/dataFiles/currentEmotion.txt",'w')
		emotionFile.write("happy")
		emotionFile.close()

		statusFile = open("main/dataFiles/emotionTrackerStatus.txt",'w')
		statusFile.write("OFF")
		statusFile.close()

		messageFile = open("main/dataFiles/messages.txt","w")
		messageFile.write("")
		messageFile.close()

		return render(request,'Html/video.html')
	else:
		return redirect("main:landingpage")

def join_stream(request):
	if (request.user.is_authenticated):
		return render(request, "Html/streamid.html")
	else:
		return redirect("main:landingpage")

def gen(camera):
	while True:
		frame = camera.get_frame()
		latest_frame = frame
		yield (b'--frame\r\n'
				b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')

def ex_stream():
	while True:
		fake = getFake()
		yield (b'--frame\r\n'
				b'Content-Type: image/jpeg\r\n\r\n' + fake + b'\r\n\r\n')

def send_stream(request):
	return StreamingHttpResponse(ex_stream(),
			content_type='multipart/x-mixed-replace; boundary=frame')

def video_feed(request):
	return StreamingHttpResponse(gen(VideoCamera()),
					content_type='multipart/x-mixed-replace; boundary=frame')

@csrf_protect
def change_emotion(request):
	if request.method == 'POST':
		emotion = request.POST['emotion']
		print(emotion)
		emotionFile = open("main/dataFiles/currentEmotion.txt",'w')
		emotionFile.write(emotion)
		emotionFile.close()

		return HttpResponse('')


def change_emotion_tracker_status(request):
	if request.method == 'POST':
		status = request.POST['status']

		statusFile = open("main/dataFiles/emotionTrackerStatus.txt","w")
		statusFile.write(status)
		statusFile.close()

		return HttpResponse('')


def writeMessage(request):
	if request.method == 'POST':
		message = request.POST['message']
		if message != "":
			messageFile = open("main/dataFiles/messages.txt","a")
			messageFile.write("\n")
			messageFile.write("<b>"+request.user.username+"</b> : " + message + "<br>")
			messageFile.close()
			return HttpResponse('')



def readMessageViewer(request):
	if request.method == 'GET':
		f = open('main/dataFiles/messages.txt', 'r')
		file_content = f.read()
		f.close()
		return HttpResponse(file_content, content_type="text/plain")

main/templates/Html/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
	<head>
		<title>Welcome to Facade</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
		<link rel="stylesheet" href="../../static/index.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

	</head>
	<body>
		{% include 'main/includes/navbar.html' %}
		{% include 'main/includes/messages.html' %}
		<div class="row">
			<div class="column left-col" >
				<a href="/stream" class = "button1">Start a new stream</a>
			</div>
			<div class="column right-col">
				<a href="/join" class = "button2">Join this stream</a>
			</div>
		</div>
	</body>
</html>

main/templates/Html/login.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
	<head>
		<title>Login</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
	</head>
	<body>
		{% include 'main/includes/navbar.html' %}
		{% include 'main/includes/messages.html' %}
		{% block content %}

	    <div class="container">
	        <form method="POST">
	        {% csrf_token %}
	        {{form.as_p}}
	            <button style="background-color:#F4EB16; color:blue" class="btn btn-outline-info" type="submit">Login</button>
	        </form>
	        Don't have an account? <a href="/register" target="blank"><strong>Register here</strong></a>!
	    </div>

		{% endblock %}
	</body>
</html>

main/templates/Html/register.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
	<head>
		<title>Login</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

	</head>
	<body>
		{% include 'main/includes/navbar.html' %}
		{% include 'main/includes/messages.html' %}
		{% block content %}
		<br>
		<div class="container">
			<form method="POST">
				{% csrf_token %}
				{{form.as_p}}
				<button style="background-color:#F4EB16; color:blue" class="btn btn-outline-info" type="submit">Sign Up</button>
			</form>

			If you already have an account <a href="/login" target="blank"><strong>login</strong></a> instead.
		</div>
		{% endblock %}
	</body>
</html>

main/templates/Html/streamid.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<meta name="viewport" content="width=device-width, initial-scale=1">

<head>
	<title>Welcome to Facade</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<<<<<<< HEAD
=======
	<!-- <link rel="stylesheet" href="../../static/chat.css"> -->
>>>>>>> 862707cabd7bee94175830a09d4adec5c83f328c
	<link rel="stylesheet" href="../../static/stream.css">

</head>

<body>
	{% include 'main/includes/navbar.html' %}
	{% include 'main/includes/messages.html' %}
	<div class="flex-container">
		<div class="stream">
			<img src="{% url 'main:viewstream' %}" alt="video_image" id="main_feed" height='480' width="480">
		</div>
		<div class="chatbox" id="myForm">
			<h1>Comments</h1>
			<div class="chats">
				<p id="chats"></p>
			</div>

			<div class="form-container">
				<input id="message" type="text" >
				<button id="send" type="submit" class ="btn btn-primary">Send</button>
			</div>
		</div>
	</div>

</body>
<script>
	function openForm() {
		document.getElementById("myForm").style.display = "block";
	}

	function closeForm() {
		document.getElementById("myForm").style.display = "none";
	}

	$("#send").click(function(e) {
		$.ajax({
			type: 'POST',
			url: 'writeMessage',
			data: {
				message: document.getElementById('message').value,
				csrfmiddlewaretoken: '{{ csrf_token }}',
			},
			success: function() {}
		});
		document.getElementById('message').value = "";
	});


	var intervalId = window.setInterval(function() {
		$.ajax({
			type: "GET",
			url: "readMessageViewer",
			success: function(data) {
				document.getElementById('chats').innerHTML = data;
			},
			error: function(e) {
				// alert("error", e);
			}
		});
	}, 500);
</script>

</html>

main/templates/Html/video.html
<!DOCTYPE html>

<html>

<head>
	{% load static %}

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<title>Digital Ventriloquism</title>
	<link rel="stylesheet" href="../../static/style.css">
	<script src="https://kit.fontawesome.com/abe4a76727.js" crossorigin="anonymous"></script>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
	<script src="{% static '/js/effects.js' %}"></script>
	<script src="{% static '/js/jungle.js' %}"></script>
	<script src="{% static 'js/others.js' %}"></script>
	<script src="{% static 'js/visualizer/base.js' %}"></script>
	<script src="{% static 'js/visualizer/cameracontroller.js' %}"></script>

	<script src="{% static 'js/visualizer/matrix4x4.js' %}"></script>

	<script src="{% static 'js/visualizer/visualizer.js' %}"></script>
	<script src="{% static 'js/visualizer/shader.js' %}"></script>
	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
	{% include 'main/includes/navbar.html' %} {% include 'main/includes/messages.html' %}
	<div class="projectTitleContainer">
		<h1 class="projectTitle" style="color: white;">Digital Ventriloquism</h1>
	</div>
	<div id="left" class="emotions-n-sounds">
		<div class="emotions_options">
			<div class="emotions-heading" style="border: solid;text-align: center; font-size: 25px;  border-collapse: collapse;">
				Change displayed emotion
			</div>
			<div class="emotions" style="border:solid;">
				<i class="fas fa-angry fa-6x" style="color : #660000" onclick="changeFaceExpression('angry');"></i>
				<i class="fas fa-frown fa-6x" style="color : #1a2f26;" onclick="changeFaceExpression('sad');"></i>
				<i class="fas fa-grin fa-6x" style="color : #FFD31D" onclick="changeFaceExpression('happy');"></i>
				<span style="font-size: 1.75em;">and many more..</span>
			</div>
		</div>
		<div class="audio-options" style="border:solid">
			<p class="centered_div">Play default sound</p>
			<br>
			<div class="centered_div">
				<button class="round_button">Laugh</button>
			</div>
			<br>
			<div class="centered_div">
				<button class="round_button">Cry</button>
			</div>
			<br>
			<div class="centered_div">
				<button class="round_button">Growl</button>
			</div>
			<br>
			<div class="centered_div">
				<button class="round_button">Snarl</button>
			</div>
		</div>
	</div>
	<div id='av' class="av_stream">
		<img src="{% url 'main:video_feed' %}" alt="video_image" id="main_feed" height='480' width="480">
		<span class="fa-stack fa-2x" id="micElements" onclick="toggleMic()" style="margin-bottom: 5px;">
			<i class = "fas fa-microphone fa-stack-1x" id = "micBase"></i>
			<i  style = "color:Tomato" id = "micBan"></i>
		</span>
		<div id="arranger" style="height: 0px">
			<canvas id="view1"></canvas><br>
			<canvas id="view2"></canvas>
		</div>
		<div id="effectMix">
			Effect:
			<select id="effect">
				<option>Delay </option>
				<option>Telephone </option>
				<option>Pitch Shifter </option>
				<option>Ping-pong delay</option>
			</select> &nbsp;&nbsp; Effect Mix:
			<input type="range" min="0.0" max="1.0" step="0.01" value="1.0" style="height: 20px; width: 200px;" onInput="crossfade( event.target.value );"> &nbsp;&nbsp; Mono input: <input type="checkbox" checked onchange="toggleMono()">
		</div>
		<div id="controls">
			<div id="delayControls">A basic digital delay.<br> Delay time: <input id="dtime" type="range" min="0.01" max="3" step="0.01" value="0.15" style="height: 20px; width: 200px" onInput="if (dtime) dtime.delayTime.value = event.target.value;"><br> Regen: <input id="dregen"
				type="range" min="0.0" max="1.0" step="0.01" value="0.75" style="height: 20px; width: 200px;" onInput="if (dregen) dregen.gain.value = event.target.value;">
			</div>
			<div id="telephoneControls">This effect pairs a low-pass and a high-pass filter to "telephonize" a sound - removing the high and low frequencies.
			</div>
			<div id="doublerControls">A pitch-shifting effect, using sample-accurate delay ramping. Defaults to one octave down.<br> Pitch-shift: <input id="octpitch" type="range" min="-1" max="1" step="0.05" value="-1" style="height: 20px; width: 200px;" onInput="if (effect.setPitchOffset) effect.setPitchOffset(event.target.value);"><br>
			</div>
			<div id="pingpongControls">A ping-pong delay - bounces stereo channels. Most noticeable with mono signal.<br>
			</div>
		</div>
	</div>
	<div id="right" class="other_controls">
		<div class="centered_div">
			<span style="font-size: 25px; padding-left: 0px; color: white;">Live emotion tracking</span>&nbsp&nbsp&nbsp
			<i style="color: black;" class="fas fa-toggle-off fa-3x" onclick="toggleEmotionTracker();" id="emotionTracker"></i>
		</div>
		<div class="chatbox" id="myForm">
			<h1 style="color: white;">Comments</h1>
			<div class="chats">
				<p id="chats"></p>
			</div>

			<div class="form-container">
				<input id="message" type="text" >
				<button id="send" type="submit" class ="btn btn-primary">Send</button>
			</div>
		</div>
	</div>



</body>

<script>
	function changeFaceExpression(selectedExpression) {
		var newExpression = selectedExpression;
		console.log(selectedExpression);
		$.ajax({
			type: 'POST',
			url: 'emotion-change',
			data: {
				emotion: newExpression,
				csrfmiddlewaretoken: '{{ csrf_token }}',
			},
			success: function() {}
		});
	}

	function toggleEmotionTracker() {
		var temp = document.getElementById("emotionTracker").getAttribute("class");
		var emotion_tracker_status = temp.search("off");
		if (emotion_tracker_status == -1) {
			emotion_tracker_status = "OFF";
			document.getElementById("emotionTracker").removeAttribute("class");
			document.getElementById("emotionTracker").setAttribute("class", "fas fa-toggle-off fa-3x");
		} else {
			emotion_tracker_status = "ON";
			document.getElementById("emotionTracker").removeAttribute("class");
			document.getElementById("emotionTracker").setAttribute("class", "fas fa-toggle-on fa-3x");
		}
		$.ajax({
			type: 'POST',
			url: 'emotion-tracker-status-change',
			data: {
				status: emotion_tracker_status,
				csrfmiddlewaretoken: '{{ csrf_token }}',
			},
			success: function() {}
		});
	}



	// chatbox
	$("#send").click(function(e) {
		$.ajax({
			type: 'POST',
			url: 'writeMessage',
			data: {
				message: document.getElementById('message').value,
				csrfmiddlewaretoken: '{{ csrf_token }}',
			},
			success: function() {}
		});
		document.getElementById('message').value = "";
	});


	var intervalId = window.setInterval(function() {
		console.log('hello');
		$.ajax({
			type: "GET",
			url: "readMessageViewer",
			success: function(data) {
				document.getElementById('chats').innerHTML = data;
			},
			error: function(e) {
			}
		});
	}, 500);
</script>

</html>

main/templates/main/includes/base.html
<!DOCTYPE html>

{% load static %}

<html>
<head>
    <meta charset="UTF-8">
	<link rel="stylesheet" href="{% static "css/chat_style.css" %}" type="text/css" media="screen" />
	<script src="{% static "js/jquery-1.12.2.min.js" %}" type="text/javascript"></script>
	<script src="{% static "js/reconnecting-websocket.min.js" %}" type="text/javascript"></script>
</head>
<body>
	<section>
		{% block content %}
		{% endblock %}
	</section>
	{% block extra_body %}{% endblock %}
</body>
</html>

main/templates/main/includes/chat.html
{% extends "main/includes/base.html" %}

{% block content %}

    <ul class="rooms">
        {% for room in rooms %}
            <li class="room-link" data-room-id="{{ room.id }}">{{ room }}</li>
        {% empty %}
            <p class="empty">No chat rooms defined. Maybe make some in the <a href="{% url 'admin:index' %}">admin</a>?</p>
        {% endfor %}
    </ul>

    <div id="chats">
    </div>

{% endblock %}


{% block extra_body %}
    <script>
        $(function () {
            // Correctly decide between ws:// and wss://
            var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
            var ws_path = ws_scheme + '://' + window.location.host + "/chat/stream/";
            console.log("Connecting to " + ws_path);
            var socket = new ReconnectingWebSocket(ws_path);

            // Handle incoming messages
            socket.onmessage = function (message) {
                // Decode the JSON
                console.log("Got websocket message " + message.data);
                var data = JSON.parse(message.data);
                // Handle errors
                if (data.error) {
                    alert(data.error);
                    return;
                }
                // Handle joining
                if (data.join) {
                    console.log("Joining room " + data.join);
                    var roomdiv = $(
                            "<div class='room' id='room-" + data.join + "'>" +
                            "<h2>" + data.title + "</h2>" +
                            "<div class='messages'></div>" +
                            "<form><input><button>Send</button></form>" +
                            "</div>"
                    );
                    // Hook up send button to send a message
                    roomdiv.find("form").on("submit", function () {
                        socket.send(JSON.stringify({
                            "command": "send",
                            "room": data.join,
                            "message": roomdiv.find("input").val()
                        }));
                        roomdiv.find("input").val("");
                        return false;
                    });
                    $("#chats").append(roomdiv);
                    // Handle leaving
                } else if (data.leave) {
                    console.log("Leaving room " + data.leave);
                    $("#room-" + data.leave).remove();
                    // Handle getting a message
                } else if (data.message || data.msg_type != 0) {
                    var msgdiv = $("#room-" + data.room + " .messages");
                    var ok_msg = "";
                    // msg types are defined in chat/settings.py
                    // Only for demo purposes is hardcoded, in production scenarios, consider call a service.
                    switch (data.msg_type) {
                        case 0:
                            // Message
                            ok_msg = "<div class='message'>" +
                                    "<span class='username'>" + data.username + "</span>" +
                                    "<span class='body'>" + data.message + "</span>" +
                                    "</div>";
                            break;
                        case 1:
                            // Warning / Advice messages
                            ok_msg = "<div class='contextual-message text-warning'>" + data.message +
                                    "</div>";
                            break;
                        case 2:
                            // Alert / Danger messages
                            ok_msg = "<div class='contextual-message text-danger'>" + data.message +
                                    "</div>";
                            break;
                        case 3:
                            // "Muted" messages
                            ok_msg = "<div class='contextual-message text-muted'>" + data.message +
                                    "</div>";
                            break;
                        case 4:
                            // User joined room
                            ok_msg = "<div class='contextual-message text-muted'>" + data.username +
                                    " joined the room!" +
                                    "</div>";
                            break;
                        case 5:
                            // User left room
                            ok_msg = "<div class='contextual-message text-muted'>" + data.username +
                                    " left the room!" +
                                    "</div>";
                            break;
                        default:
                            console.log("Unsupported message type!");
                            return;
                    }
                    msgdiv.append(ok_msg);

                    msgdiv.scrollTop(msgdiv.prop("scrollHeight"));
                } else {
                    console.log("Cannot handle message!");
                }
            };

            // Says if we joined a room or not by if there's a div for it
            inRoom = function (roomId) {
                return $("#room-" + roomId).length > 0;
            };

            // Room join/leave
            $("li.room-link").click(function () {
                roomId = $(this).attr("data-room-id");
                if (inRoom(roomId)) {
                    // Leave room
                    $(this).removeClass("joined");
                    socket.send(JSON.stringify({
                        "command": "leave",
                        "room": roomId
                    }));
                } else {
                    // Join room
                    $(this).addClass("joined");
                    socket.send(JSON.stringify({
                        "command": "join",
                        "room": roomId
                    }));
                }
            });

            // Helpful debugging
            socket.onopen = function () {
                console.log("Connected to chat socket");
            };
            socket.onclose = function () {
                console.log("Disconnected from chat socket");
            }
        });
    </script>
{% endblock %}

main/templates/main/includes/messages.html
{% if messages %}
	{% for message in messages %}
		{% if message.tags == 'success'%}
			<div class="alert alert-success alert-dismissible fade show" role="alert">
				{{message}}
			</div>
		{% elif message.tags == 'info'%}
			<div class="alert alert-info alert-dismissible fade show" role="alert">
				{{message}}
			</div>
    	{% elif message.tags == 'warning'%}
			<div class="alert alert-warning alert-dismissible fade show" role="alert">
				{{message}}
			</div>
		{% elif message.tags == 'error'%}
			<div class="alert alert-danger alert-dismissible fade show" role="alert">
				{{message}}
			</div>
		{% endif %}
	{% endfor %}
{% endif %}

main/templates/main/includes/navbar.html
<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		<div class="navbar-header">
			<a class="navbar-brand" href="#">Facade</a>
		</div>
		<ul class="nav navbar-nav">
			<li class="active"><a href="/#">Home</a></li>
			<li><a href="stream">Start a stream</a></li>
			<li><a href="join">Join a stream</a></li>
		</ul>
		<ul class="nav navbar-nav navbar-right">
			{% if user.is_authenticated %}
			<li><a href="/logout"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
			{% else %}
			<li><a href="/register"><span class="glyphicon glyphicon-user"></span>Sign up!</a></li>
			<li><a href="/login"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
			{% endif %}
		</ul>
	</div>
</nav>